apiVersion: apps/v1
kind: Deployment
metadata:
  name: driveguard-backend
  labels:
    app: driveguard-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: driveguard-backend
  template:
    metadata:
      labels:
        app: driveguard-backend
    spec:
      containers:
        - name: backend
          image: driveguard/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: driveguard-secrets
                  key: database_url
            - name: MQTT_BROKER_HOST
              value: driveguard-mqtt
            - name: MQTT_BROKER_PORT
              value: "1883"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: driveguard-backend
spec:
  type: ClusterIP
  selector:
    app: driveguard-backend
  ports:
    - port: 8000
      targetPort: 8000
